# Generated by Django 5.1.2 on 2024-11-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karma', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('banner', models.URLField(default='https://hn12c-hackertimes.s3.us-east-1.amazonaws.com/banners/DefaultBanner.jpg')),
                ('avatar', models.URLField(default='https://hn12c-hackertimes.s3.us-east-1.amazonaws.com/avatars/DefaultProfile.png')),
                ('show_dead', models.BooleanField(default=True)),
                ('no_procrastinate', models.BooleanField(default=False)),
                ('max_visit', models.PositiveIntegerField(default=20)),
                ('min_away', models.PositiveIntegerField(default=180)),
                ('delay', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('urlDomain', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='News.comments')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
    ]
