# Generated by Django 4.2.11 on 2024-11-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karma', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, default='banners/DefaultBanner.jpg', null=True, upload_to='banners/')),
                ('avatar', models.ImageField(blank=True, default='avatars/DefaultProfile.png', null=True, upload_to='avatars/')),
                ('show_dead', models.BooleanField(default=True)),
                ('no_procrastinate', models.BooleanField(default=False)),
                ('max_visit', models.PositiveIntegerField(default=20)),
                ('min_away', models.PositiveIntegerField(default=180)),
                ('delay', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('urlDomain', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
    ]
