# Generated by Django 4.2.16 on 2024-11-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
    ]
