# Generated by Django 5.1.2 on 2024-11-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_comments', to='News.customuser'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
