# Generated by Django 5.1.2 on 2024-10-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
