# Generated by Django 4.2.16 on 2024-11-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_news_voters'),
        ('News', '0004_alter_hiddennews_unique_together'),
    ]

    operations = [
    ]
