# Generated by Django 3.2.25 on 2024-10-17 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_hour',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 7, 16, 37, 329225)),
        ),
    ]
