# Generated by Django 5.1.2 on 2024-11-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_comments_voters_alter_comments_published_date_and_more'),
        ('News', '0005_merge_20241110_2254'),
    ]

    operations = [
    ]
