# Generated by Django 3.2.25 on 2024-10-17 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_news_published_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_hour',
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 7, 17, 21, 718813)),
        ),
    ]
