# Generated by Django 5.1.2 on 2024-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_merge_20241111_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_comments',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='News.comments'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_news',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='News.news'),
        ),
    ]
