# Generated by Django 5.1.2 on 2024-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='urlDomain',
            field=models.CharField(default='exemple.org', max_length=200),
            preserve_default=False,
        ),
    ]
