<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-11 21:36
=======
# Generated by Django 4.2.16 on 2024-11-11 22:31
>>>>>>> feature/task-#55-Pagina-threads

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_customuser_favorite_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
