# Generated by Django 4.2.16 on 2024-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='description',
        ),
        migrations.AddField(
            model_name='thread',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='threads', to='News.comments'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
