# Generated by Django 5.1.2 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_news_urldomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karma', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('show_dead', models.BooleanField(default=True)),
                ('no_procrastinate', models.BooleanField(default=False)),
                ('max_visit', models.PositiveIntegerField(default=20)),
                ('min_away', models.PositiveIntegerField(default=180)),
                ('delay', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
