# Generated by Django 3.2.25 on 2024-10-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karma', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('show_dead', models.BooleanField(default=True)),
                ('no_procrastinate', models.BooleanField(default=False)),
                ('max_visit', models.PositiveIntegerField(default=20)),
                ('min_away', models.PositiveIntegerField(default=180)),
                ('delay', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='News',
            new_name='New',
        ),
        migrations.AddField(
            model_name='comments',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser'),
        ),
    ]
