# Generated by Django 3.2.25 on 2024-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20241021_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
