# Generated by Django 4.2.16 on 2024-11-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_remove_thread_author_thread_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
    ]
