# Generated by Django 5.1.2 on 2024-10-23 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_alter_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.customuser')),
            ],
        ),
    ]
