# Generated by Django 5.1.2 on 2024-10-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_news_is_hidden_alter_news_text_alter_news_url_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_hidden',
        ),
    ]
