# Generated by Django 4.2.16 on 2024-11-20 15:15

from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    CustomUser = apps.get_model('News', 'CustomUser')
    for user in CustomUser.objects.all():
        user.api_key = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ('News', '0012_thread_voters_delete_search'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='voters',
        ),
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_uuid),
    ]