# Generated by Django 5.1.2 on 2024-10-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_remove_news_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
